export const NorthAmerica = [
  'British Columbia',
  'Alberta',
  'Saskatchewan',
  'Manitoba',
  'Ontario',
  'Quebec',
  'New Brunswick',
  'Newfoundland and Labrador',
  'Nova Scotia',
  'Prince Edward Island',
  'Yukon',
  'Northwest Territories',
  'Alaska',
  'Washington',
  'Oregon',
  'California',
  'Hawaii',
  'Idaho',
  'Sierra Nevada',
  'Nevada',
  'Utah',
  'Arizona',
  'Montana',
  'Wyoming',
  'Colorado',
  'New Mexico',
  'North Dakota',
  'South Dakota',
  'Nebraska',
  'Kansas',
  'Texas',
  'Minnesota',
  'Iowa',
  'Missouri',
  'Arkansas',
  'Wisconsin',
  'Illinois',
  'Tennessee',
  'Alabama',
  'Michigan',
  'Indiana',
  'Kentucky',
  'Georgia',
  'Maine',
  'Vermont',
  'New Hampshire',
  'New York',
  'New Jersey',
  'Rhode Island',
  'Massachusetts',
  'Connecticut',
  'Ohio',
  'Pennsylvania',
  'Maryland',
  'West Virginia',
  'Virginia',
  'North Carolina',
  'Greenland',
];

export const Europe = [
  'Andorra',
  'Russia',
  'Slovakia',
  'Slovenia',
  'Portugal',
  'Romania',
  'Finland',
  'Estonia',
  'Czech Republic',
  'Belarus',
  'Kazakhstan',
  'Belgium',
  'Sweden',
  'Lower Austria',
  'Turkey',
  'Ukraine',
  'Greece',
  'Macedonia',
  'Poland',
  'Upper Austria',
  'Norway',
  'Italy',
  'Latvia',
  'Hungary',
  'Ireland',
  'Iceland',
  'Denmark',
  'Lithuania',
  'Liechtenstein',
  'Kosovo',
  'Montenegro',
  'Cyprus',
  'Hauts-de-France',
  'Central Switzerland',
  'Netherlands',
  'United Kingdom',
  'Pays-de-la-Loire',
  'Nouvelle-Aquitaine',
  'Paris-Isle-of-France',
  'Bosnia and Herzegovina',
  'Vienna',
  'Bulgaria',
  'Croatia',
  'Normandy',
  'Allgäu Alps',
  'Provence-Alpes-Azur',
  'Rhone-Alps',
  'Franche-comte',
  'Valais and Vaud',
  'Brittany',
  'Kärnten (Carinthia)',
  'Salzburg',
  'Styria',
  'Bavarian Alps',
  'Eastern Switzerland',
  'Corsica',
  'Tyrol',
  'Bernese Oberland',
  'Occitanie (Pyrenees)',
  'Vorarlberg',
  'Central Uplands',
  'Grand Est (Alsace, Lorraine, Champagne-Ardenne)',
  'Burgundy',
  'Graubünden',
  'Massif Central',
];

export const Asia = [
  'Tajikistan',
  'Mongolia',
  'Iraq',
  'Hokkaido (北海道)',
  'Indonesia',
  'Serbia',
  'India',
  'Iran',
  'Armenia',
  'Tōhoku - Aomori',
  'Tōhoku - Iwate',
  'Tōhoku - Miyagi',
  'Tōhoku - Akita',
  'Tōhoku - Yamagata',
  'Tōhoku - Fukushima',
  'Kantō - Ibaraki',
  'Kantō - Tochigi',
  'Kantō - Gunma',
  'Kantō - Saitama',
  'Kantō - Kanagawa',
  'Chūbu - Niigata',
  'Chūbu - Toyama',
  'Chūbu - Ishikawa',
  'Chūbu - Fukui',
  'Chūbu - Shizuoka',
  'Chūbu - Yamanashi',
  'Chūbu - Nagano',
  'Chūbu - Gifu',
  'Chūbu - Aichi',
  'Chūbu - Mie',
  'Kansai - Shiga',
  'Kansai - Kyoto',
  'Kansai - Hyōgo',
  'Kansai - Nara',
  'Chugoku (中国地方)',
  'Shikoku (四国)',
  'Kyushu (九州) ',
  'Azerbaijan',
  'North Korea',
  'China',
  'Israel',
  'South Korea',
  'Lebanon',
  'Pakistan',
  'United Arab Emirates',
  'Kyrgyzstan',
  'Uzbekistan',
  'Cantabrian Mountains',
  'Iberian Mountains',
  'Sistema Central',
  'Ticino',
];

export const SouthAmerica = [
  'Argentina',
  'Brazil',
  'Bolivia',
  'Chile',
  'Mexico',
  'Venezuela',
];

export const Other = [
  'Fantasy Land',
  'Pyrenees',
  'Lesotho',
  'Morocco',
  'Australia',
  'New Zealand',
  'Algeria',
  'British Antarctic Territory',
  'South Africa',
];
