const Canada = [
  'British Columbia',
  'Alberta',
  'Saskatchewan',
  'Manitoba',
  'Ontario',
  'Quebec',
  'Prince Edward Island',
  'Newfoundland and Labrador',
  'Nova Scotia',
  'New Brunswick'
  'Yukon',
  'Northwest Territories',
  //Nunavut?
];

const USA = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming'
];

const Asia = [

];

const Other = [
  'Russia',
  'Andorra',
  'Belgium',
  'Morocco',
  'Lesotho',
  'Belarus',
  'Bosnia and Herzegovina',
  'Bulgaria',
  'Croatia',
  'Cyprus',
  'Czech Republic',
  'Estonia',
  'Finland',
  'Macedonia',
  'Norway',
  'Portugal',
  'Romania',
  'Fantasy Land',
  'Slovakia',
  'Slovenia',
  'Pyrenees',
  'Cantabrian Mountains',
  'Sistema Central',
  'Iberian Mountains',
  'Sweden',
  'Turkey',
  'Ukraine',
  'Latvia',
  'Greece',
  'Iceland',
  'Montenegro',
  'Liechtenstein',
  'Hungary',
  'Kyrgyzstan',
  'Uzbekistan',
  'Kosovo',
  'British Antarctic Territory',
  'Vorarlberg',
  'Ticino',
  'Lithuania',
  'Azerbaijan',
  'Greenland',
  'Mexico',
  'Ireland',
  'North Korea',
  'Denmark',
  'Tajikistan',
  'Mongolia',
  'Algeria',
  'Iraq',
  'Netherlands',
  'Normandy',
  'Pays-de-la-Loire',
  'Nouvelle-Aquitaine',
  'Hauts-de-France',
  'Paris-Isle-of-France',
  'Brittany',
  'Chile',
  'New Zealand',
  'Australia',
  'India',
  'Iran',
  'South Africa',
  'Argentina',
  'Bolivia',
  'Brazil',
  'Venezuela',
  'China',
  'Armenia',
  'Israel',
  'Kazakhstan',
  'South Korea',
  'Lebanon',
  'Pakistan',
  'United Arab Emirates',
];

const Japan = [
  'Tōhoku - Aomori',
  'Tōhoku - Iwate',
  'Tōhoku - Miyagi',
  'Tōhoku - Akita',
  'Tōhoku - Yamagata',
  'Tōhoku - Fukushima',
  'Kantō - Ibaraki',
  'Kantō - Tochigi',
  'Kantō - Gunma',
  'Kantō - Saitama',
  'Kantō - Kanagawa',
  'Chūbu - Niigata',
  'Chūbu - Toyama',
  'Chūbu - Ishikawa',
  'Chūbu - Fukui',
  'Chūbu - Shizuoka',
  'Chūbu - Yamanashi',
  'Chūbu - Nagano',
  'Chūbu - Gifu',
  'Chūbu - Aichi',
  'Chūbu - Mie',
  'Kansai - Shiga',
  'Kansai - Kyoto',
  'Kansai - Hyōgo',
  'Kansai - Nara',
  'Chugoku (中国地方)',
  'Shikoku (四国)',
  'Kyushu (九州) ',
  'Hokkaido (北海道)'
];

const Europe = [
  'Central Switzerland',
  'Kärnten (Carinthia)',
  'Lower Austria',
  'Salzburg',
  'Styria',
  'Tyrol',
  'Upper Austria',
  'Vienna',
  'Provence-Alpes-Azur',
  'Rhone-Alps',
  'United Kingdom',
  'Poland',
  'Corsica',
  'Burgundy',
  'Occitanie (Pyrenees)',
  'Grand Est (Alsace, Lorraine, Champagne-Ardenne)',
  'Franche-comte',
  'Massif Central',
  'Indonesia',
  'Bavarian Alps',
  'Central Uplands',
  'Allgäu Alps',
  'Italy',
  'Valais and Vaud',
  'Bernese Oberland',
  'Graubünden',
  'Eastern Switzerland',
  'Serbia'
];

