const Canada = [
  'British Columbia',
  'Alberta',
  'Saskatchewan',
  'Manitoba',
  'Ontario',
  'Quebec',
  'Prince Edward Island',
  'Newfoundland and Labrador',
  'Nova Scotia',
  'New Brunswick'
  'Yukon',
  'Northwest Territories',
  //Nunavut?
];

const USA = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming'
];

const Europe = [
  'Russia',
  'Ukraine',
  'Pays-de-la-Loire',
  'Nouvelle-Aquitaine',
  'Hauts-de-France',
  'Paris-Isle-of-France',
  'Sweden',
  'Norway',
  'Finland',
  'Poland',
  'Italy',
  'United Kingdom',
  'Romania',
  'Belarus',
  'Kazakhstan',
  'Greece',
  'Bulgaria',
  'Iceland',
  'Hungary',
  'Portugal',
  'Lower Austria',
  'Upper Austria',
  'Czech Republic',
  'Serbia'
  'Ireland',
  'Lithuania',
  'Latvia',
  'Croatia',
  'Bosnia and Herzegovina',
  'Slovakia',
  'Estonia',
  'Denmark',
  'Central Switzerland',
  'Eastern Switzerland',
  'Netherlands',
  'Belgium',
  'Andorra',
  'Morocco',
  'Slovenia',
  'Armenia',
  'Macedonia',
  'Turkey',
  'Montenegro',
  'Kosovo',
  'Azerbaijan',
  'Cyprus',
  'Liechtenstein'
  'Salzburg',
  'Vienna',
  'Provence-Alpes-Azur',
  'Rhone-Alps',
];

const other = [
  'Kärnten (Carinthia)',
  'Styria',
  'Tyrol',
  'Corsica',
  'Burgundy',
  'Occitanie (Pyrenees)',
  'Grand Est (Alsace, Lorraine, Champagne-Ardenne)',
  'Franche-comte',
  'Massif Central',
  'Indonesia',
  'Bavarian Alps',
  'Central Uplands',
  'Allgäu Alps',
  'Valais and Vaud',
  'Bernese Oberland',
  'Graubünden',
  'Lesotho',
  'Fantasy Land',
  'Pyrenees',
  'Cantabrian Mountains',
  'Sistema Central',
  'Iberian Mountains',
  'Kyrgyzstan',
  'Uzbekistan',
  'British Antarctic Territory',
  'Vorarlberg',
  'Ticino',
  'Greenland',
  'Mexico',
  'North Korea',
  'Tajikistan',
  'Mongolia',
  'Algeria',
  'Iraq',
  'Normandy',
  'Brittany',
  'Chile',
  'India',
  'Iran',
  'South Africa',
  'Argentina',
  'Bolivia',
  'Brazil',
  'Venezuela',
  'China',
  'Israel',
  'South Korea',
  'Lebanon',
  'Pakistan',
  'United Arab Emirates',
];

const NZ_Aus = [
  'New Zealand',
  'Australia',
];

const Japan = [
  'Tōhoku - Aomori',
  'Tōhoku - Iwate',
  'Tōhoku - Miyagi',
  'Tōhoku - Akita',
  'Tōhoku - Yamagata',
  'Tōhoku - Fukushima',
  'Kantō - Ibaraki',
  'Kantō - Tochigi',
  'Kantō - Gunma',
  'Kantō - Saitama',
  'Kantō - Kanagawa',
  'Chūbu - Niigata',
  'Chūbu - Toyama',
  'Chūbu - Ishikawa',
  'Chūbu - Fukui',
  'Chūbu - Shizuoka',
  'Chūbu - Yamanashi',
  'Chūbu - Nagano',
  'Chūbu - Gifu',
  'Chūbu - Aichi',
  'Chūbu - Mie',
  'Kansai - Shiga',
  'Kansai - Kyoto',
  'Kansai - Hyōgo',
  'Kansai - Nara',
  'Chugoku (中国地方)',
  'Shikoku (四国)',
  'Kyushu (九州) ',
  'Hokkaido (北海道)'
];


